/*
 * Copyright (c) 2024 Auxio Project
 * DialogAlbumExtensions.kt is part of Auxio.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package org.oxycblt.auxio.dialogalbums

import org.oxycblt.musikr.Album
import org.oxycblt.musikr.Genre
import org.oxycblt.musikr.Song
import org.oxycblt.musikr.tag.Name

private const val DIALOG_STUDY_ALBUM_ARTIST = "Dialog Study"
private const val DIALOG_STUDY_GENRE = "DialogStudy"

/**
 * Returns whether this [Album] represents a dialog learning album generated by English Sentence.
 */
fun Album.isDialogStudy(): Boolean {
    if (artists.any { it.name.matchesDialogStudyArtist() }) {
        return true
    }

    return songs.any(Song::isDialogStudySong)
}

private fun Song.isDialogStudySong() = genres.any(Genre::isDialogStudyGenre)

private fun Genre.isDialogStudyGenre() = name.matchesDialogStudyTarget(DIALOG_STUDY_GENRE)

private fun Name.matchesDialogStudyArtist() = matchesDialogStudyTarget(DIALOG_STUDY_ALBUM_ARTIST)

private fun Name.matchesDialogStudyTarget(target: String) =
    this is Name.Known && raw.equals(target, ignoreCase = true)
